# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  commands:
    # install fabsetup and devel dependencies including sphinx tools
    - pip3.9 install --upgrade -e .[devel]

    # enable commands sphinx-apidoc and sphinx-build
    - asdf reshim

    # apply same steps as described in docs/development.md

    # include README
    - ln -s ../README.md  docs/

    # update api docs structure
    - rm -rf docs/api && sphinx-apidoc -o docs/api --module-first fabsetup

    # apply tweaks
    # commands syntax needs to be different
    # cf. https://github.com/readthedocs/readthedocs.org/issues/9397
    - sed -i "/Submodules/{ N; s/.*----------//; }"  docs/api/fabsetup.fabutils.rst
    - sed -i "/Submodules/{ N; s/.*----------//; }"  docs/api/fabsetup.rst
    - sed -i "/Submodules/{ N; s/.*----------//; }"  docs/api/fabsetup.utils.rst
    - sed -i "s/fabsetup package/fabsetup API/" docs/api/fabsetup.rst
    - sed -i "s/Subpackages/Submodules/" docs/api/fabsetup.rst
    - sed -i "s/ package$//" docs/api/fabsetup.fabutils.rst
    - sed -i "s/ package$//" docs/api/fabsetup.utils.rst
    - sed -i "s/ module$//g" docs/api/fabsetup.fabutils.rst
    - sed -i "s/ module$//g" docs/api/fabsetup.rst
    - sed -i "s/ module$//g" docs/api/fabsetup.utils.rst
    - rm docs/api/modules.rst

    # run sphinx
    - cd docs && make clean html; cd ..

    # create symlink for readthedocs upload
    - ln -s docs/_build/ _readthedocs
    - ls -ahl docs/_build || true
    - ls -ahl docs/_build/html || true
    - ls -ahl _readthedocs || true
    - ls -ahl _readthedocs/ || true
    - ls -ahl _readthedocs/html || true
    - pwd
