# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  commands:
    - pip3.9 install --upgrade -e .[devel]

    # apply same steps as described in docs/development.md

    # include README
    - ln -s ../README.md  docs/

    # update api docs structure
    # - rm -rf docs/api && sphinx-apidoc -o docs/api --module-first fabsetup
    - rm -rf docs/api && python3.9 -m sphinx.ext.apidoc -o docs/api --module-first fabsetup

    # apply tweaks
    # commands dialect needs to be different
    # cf. https://github.com/readthedocs/readthedocs.org/issues/9397
    # bash -c 'sed -i "/Submodules/{ N; s/.*----------//; }"  docs/api/fabsetup.fabutils.rst docs/api/fabsetup.rst docs/api/fabsetup.utils.rst'
    - sed -i "s/fabsetup package/fabsetup API/" docs/api/fabsetup.rst
    - sed -i "s/Subpackages/Submodules/" docs/api/fabsetup.rst
    - bash -c 'sed -i "s/ package$//" docs/api/fabsetup.fabutils.rst docs/api/fabsetup.utils.rst'
    - bash -c 'sed -i "s/ module$//g" docs/api/fabsetup.fabutils.rst docs/api/fabsetup.rst docs/api/fabsetup.utils.rst'
    - rm docs/api/modules.rst

    # run sphinx
    - cd docs && make clean html; cd ..

    # create symlink for readthedocs upload
    - mkdir _readthedocs
    - ln -s _readthedocs/html ../docs/_build/html

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf
